### PR TITLE
Link form view page from rows in table, add header

### PR DESCRIPTION
**Pull request by jackielincroft**
### ℹ️ Issue

Closes #20, #22, #23

### 📝 Description

- Made child's name in each form row clickable (takes you to the form details page for that specific form)
- Added TSWGO logo and "TSWGO Admin Portal" as a header to the authed app (so clicking on that takes you back to the /all-forms page from anywhere in the authenticated site)
- Changed title on single form page to show child name instead of form id once the data has loaded

### ✔️ Verification

- Just pull down the branch and `nx frontend serve`!
Screenshot 2023-04-14 at 10 55 13 AM
Screenshot 2023-04-14 at 10 55 32 AM
Screenshot 2023-04-14 at 10 57 50 AM

### CODE REVIEW

**Comment by megandouli** [comment]
WOOT WOOT 10x UX IMPROVEMENT

**Review by megandouli — DISMISSED** [review]
WOOT WOOT 10x UX IMPROVEMENT

**Review by megandouli — COMMENTED** [review]
one question: do you want to make just the child name clickable or the entire row? If just the child name, might be nice to change the styling so it looks like a clickable link

**Review by fanzzz368 — DISMISSED** [review]

**Comment by jackielincroft** [comment]
> one question: do you want to make just the child name clickable or the entire row? If just the child name, might be nice to change the styling so it looks like a clickable link

yeah, i was considering doing the entire row but i ultimately thought just child name was enough. and i thought it looked kind of ugly when they were all underlined always lol so i went with the just underlined on hover to indicate clickable link but open to changing this later!!  im gonna do final UI/UX tweaks on sunday i think :)

**Review by megandouli — APPROVED** [review]
reviewing on my phone at gongcha LMAO

**Pull request merged**
